### ISSUE TITLE
Compilation errors in C++11

### ISSUE THREAD

**Issue by jlaumon** [electronicarts/EASTL#213]
Hello,

It seems that it doesn't compile with just C++11 (since 3.12.01 I think, but I haven't tried 3.10.00).

Most of the errors are related to the fact that constants like `is_void_v` are declared inside an ifdef, but used without ifdefs elsewhere:
https://github.com/electronicarts/EASTL/blob/fb46446bfe5ea5d840f7a1b1dd812f9d23ffde4b/include/EASTL/internal/type_fundamental.h#L38-L41

https://github.com/electronicarts/EASTL/blob/fb46446bfe5ea5d840f7a1b1dd812f9d23ffde4b/include/EASTL/internal/type_fundamental.h#L223-L227

There are also a couple of `decltype(auto)` which are C++14 only.

Is it a bug, or are you dropping C++11 support?

**Comment by rparolin** [comment]
Yes, we are no longer explicitly testing only C++11 as we've implemented C++14/17 only features.  EASTL currently requires a minimum of C++14.
