### ISSUE TITLE
is_base_of implementation is missing in type_traits.h

### ISSUE THREAD

**Issue by omersabary** [electronicarts/EASTL#209]
Hi, 

I am trying to compile EASTL in windows, and I found this ERROR: 
\EASTL-master\include\EASTL/internal/functional_base.h(44): error C2065: 'is_base_of': undeclared identifier
 I look in type_traits.h and I could not find the implementation of is_base_of. 

Thanks! 
Omer

**Comment by theryee** [comment]
It's defined here:
https://github.com/electronicarts/EASTL/blob/2d2288dbebea7907f678346450339a99d7ffbaf9/include/EASTL/internal/type_properties.h#L260

Which compiler are you using?

**Comment by omersabary** [comment]
Thanks! 

The problem was the compiler - I use old version of gcc.  
Eventually, it work with gcc/g++ 7.3.0
